### ISSUE TITLE
Cannot build `examples`

### ISSUE THREAD

**Issue by ghost** [Xilinx/xilinx-tiny-cnn#3]
Hi, I follow the build section.
> cmake .
> make

It got issues below.

> CMakeFiles/example_cifar_train.dir/examples/cifar10/train.cpp.o: In function `train_cifar10(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, double, std::ostream&)':
> 
> train.cpp:(.text+0x2163): undefined reference to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> 
> train.cpp:(.text+0x21b9): undefined reference to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> 
> train.cpp:(.text+0x2208): undefined reference to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> 
> train.cpp:(.text+0x2262): undefined reference to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> 
> train.cpp:(.text+0x2613): undefined reference to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
> 
> CMakeFiles/example_cifar_train.dir/examples/cifar10/train.cpp.o:train.cpp:(.text+0x2666): more undefined references to `tiny_cnn::CNN_LOG_VECTOR(std::vector<float, tiny_cnn::aligned_allocator<float, 64ul> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)' follow
> 
> collect2: error: ld returned 1 exit status
> 
> CMakeFiles/example_cifar_train.dir/build.make:94: recipe for target 'example_cifar_train' failed
> 
> make[2]: *** [example_cifar_train] Error 1
> 
> CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/example_cifar_train.dir/all' failed
> 
> make[1]: *** [CMakeFiles/example_cifar_train.dir/all] Error 2
> 
> Makefile:83: recipe for target 'all' failed
> 
> make: *** [all] Error 2

Thanks

**Comment by saraballeri** [comment]
Hi,
I have the same problem. Have you fixed the error?
Thanks,
Sara

**Comment by ghost** [comment]
> Hi,
> I have the same problem. Have you fixed the error?
> Thanks,
> Sara

Still waiting!
